version: '3.8'
services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j_newdb
    ports:
      - "7171:7474" # HTTP interface
      - "7272:7687" # Bolt Protocol
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH}  # Neo4j authentication
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/import
      - neo4j_plugins:/plugins
      - ./conf:/var/lib/neo4j/conf
volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
